project:
  type: website
  output-dir: docs

website:

  navbar:
    title: "<img src='img/logo.png' alt='Logo' class='logo' style='height: 50px; width: auto;'>"
    background: "white"
    foreground: "#a7a9ac"
    
    
    tools:
      - icon: facebook 
        href: https://www.facebook.com/profile.php?id=100093337606435
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/mariajpalma/Genetic_variants_datatable.git
            
  sidebar:
    style: "floating"
    foreground: "#a7a9ac"
    search: true
    alignment: right
    contents:
      - section: "Introducción"
        contents:
        - index.qmd
        - GWAS.qmd
        - VCF.qmd

      - section: "Ejercicios"
        contents:
          - Graficacion_GWAS.qmd
          - VCF_filters.qmd
  
          


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-wrap: true
    message: false
    warning: false
    fig-height: 8
    fig-width: 8
    grid: 
      body-width: 1200px
      sidebar-width: 250px
      margin-width: 200px
      gutter-width: 0.8em
    fontsize: 14pt
  
engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 120
